#MineX
messages:
  prefix: "&c&lMineX &7| "
  consoleError: "You must be a player to use this command!"
  gameCreateUsage: "Invalid command usage try: /game create <id>"
  gameExists: "A game already exists with this id!"
  gameCreating: "Creating a new game with the id {id}"
  gameTpUsage: "Invalid command usage try: /game teleport <id> <spawn>"
  noGame: "There is not a valid game with this id!"
  noSpawn: "There is not a valid spawn with this id!"
  gameAddspawnUsage: "Invalid command usage try: /game addspawn <id>"
  gameSpawnSet: "Added a new spawn location to game {id} at your location!"
  gameLobbySpawnUsage: "Invalid command usage try: /game lobby setspawn <id>"
  gameLobbySpawnSet: "Set the lobby spawn for {id} to your current location."
  gameLobbyTpUsage: "Invalid command usage try : /game lobby teleport <id>"