#MineX
messages:
  gameWorld: "&c&lMineX &7| You must be inside a game world to do this!"
  lootchestPlaced: "&c&lMineX &7| You have just placed a {type} lootchest."
  extractionCanceled: "&c&lMineX &7| Extraction canceled due to movement."
  extraction: "&c&lMineX &7| You will be extracted in {time} seconds! Do not move!"
  pos1: "&c&lMineX &7| Position 1 set."
  pos2: "&c&lMineX &7| Position 2 set."
  bankGiveUsage: "&c&lMineX &7| Invalid usage try: /bank give <amount>"
  noPermission: "&c&lMineX &7| You do not have permission for this!"
  console: "&c&lMineX &7| You must be a player to run this command!"
  gameCreateUsage: "&c&lMineX &7| Invalid usage try: /game create <id>"
  gameExists: "&c&lMineX &7| A game with this id already exists!"
  gameCreating: "&c&lMineX &7| Creating a game with the id {id}"
  addMobSpawnUsage: "&c&lMineX &7| Invalid usage try: /game addmobspawn <id> <type>"
  invalidGame: "&c&lMineX &7| No game can be found matching this id!"
  invalidMobType: "&c&lMineX &7| Invalid mob type!"
  gameTeleportUsage: "&c&lMineX &7| Invalid usage try: /game teleport <id>"
  invalidSpawn: "&c&lMineX &7| We can not find a spawn with this id!"
  regionWand: "&c&lMineX &7| You have given yourself a region wand"
  regionCreateUsage: "&c&lMineX &7| Invalid usage try: /game region create <id> <name>"
  regionCreated: "&c&lMineX &7| Created a new region with the id {id}"
  noGame: "&c&lMineX &7| You are not in a game!"
  leftGame: "&c&lMineX &7| You have left a game!"
  lootchestGiveUsage: "&c&lMineX &7| Invalid usage try: /game lootchest give <type>"
  lootchestGive: "&c&lMineX &7| You have given yourself a {type} lootchest"
  invalidType: "&c&lMineX &7| Invalid type!"
  addspawnUsage: "&c&lMineX &7| Invalid usage try: /game addsapwn <id> <name>"
  addedSpawn: "&c&lMineX &7| You have added a new spawn named {name}"

economy:
  bank: true
  item:
    material: GOLD_INGOT
    name: "&c&lMoney"
    lore:
      - "&7Use /bank to safely store this!"

lootChest:
  uncommon:
    maxItems: 6
    minItems: 3
  common:
    maxItems: 5
    minItems: 2
  rare:
    maxItems: 4
    minItems: 1
  items:
    uncommon:
      1:
        material: DIAMOND
        amount: 1
      2:
        material: STONE
        damage: 0
        amount: 10
      3:
        material: STONE_SWORD
        amount: 1
      4:
        material: DIRT
        amount: 16
    common:
      1:
        material: DIAMOND
        amount: 6
      2:
        material: STONE
        amount: 20
      3:
        material: IRON_SWORD
        amount: 1
      4:
        material: DIRT
        amount: 32
    rare:
      1:
        material: DIAMOND
        amount: 16
      2:
        material: STONE
        amount: 32
      3:
        material: DIAMOND_SWORD
        amount: 1
      4:
        material: DIRT
        amount: 32

