package minex.CustomEnchants;

public enum EffectType {

    ACTIONBAR, ADD_DURABILITY, ADD_DURABILITY_ITEM, ADD_FOOD, DAMAGE, HEAL, BLEED, BREAK, DIABLE_USE, COMMAND, CURE, CURE_PERM, DAMAGE_ARMOR, DISABLE_KNOWCKBACK, DISARM, DOUBLE_DAMAGE, EXTINGUISH, FLAME, HALF_DAMAGE, INCREASE_DAMAGE, KEEP_ON_DEATH, REVIVE, POTION, MESSAGE, TITLE;
}
