package minex.CustomEnchants;

public enum EnchantmentType {

    ARROW_HIT, ATTACK, ATTACK_MOB, BOW, BOW_MOB, BOW_SHOOT,DEATH, DEFENSE, DEFENSE_BOW, DEFENSE_MOB, EAT, STATIC, EXPLOSION, FALL_DAMAGE, FIRE, HELD, ITEM_BREAK, KILL_MOB, KILL_PLAYER, MINING, PASSIVE_DEATH, RIGHT_CLICK, SHIFT, SPRING, SWING,

    }
