#MineX
messages:
  gameWorld: "&c&lMineX &7| You must be inside a game world to do this!"
  lootchestPlaced: "&c&lMineX &7| You have just placed a {type} lootchest."
  extractionCanceled: "&c&lMineX &7| Extraction canceled due to movement."
  extraction: "&c&lMineX &7| You will be extracted in {time} seconds! Do not move!"
  pos1: "&c&lMineX &7| Position 1 set."
  pos2: "&c&lMineX &7| Position 2 set."
  bankGiveUsage: "&c&lMineX &7| Invalid usage try: /bank give <amount>"
  noPermission: "&c&lMineX &7| You do not have permission for this!"
  console: "&c&lMineX &7| You must be a player to run this command!"
  gameCreateUsage: "&c&lMineX &7| Invalid usage try: /game create <id>"
  gameExists: "&c&lMineX &7| A game with this id already exists!"
  gameCreating: "&c&lMineX &7| Creating a game with the id {id}"
  addMobSpawnUsage: "&c&lMineX &7| Invalid usage try: /game addmobspawn <id> <type>"
  invalidGame: "&c&lMineX &7| No game can be found matching this id!"
  invalidMobType: "&c&lMineX &7| Invalid mob type!"
  gameTeleportUsage: "&c&lMineX &7| Invalid usage try: /game teleport <id>"
  invalidSpawn: "&c&lMineX &7| We can not find a spawn with this id!"
  regionWand: "&c&lMineX &7| You have given yourself a region wand"
  regionCreateUsage: "&c&lMineX &7| Invalid usage try: /game region create <id> <name>"
  regionCreated: "&c&lMineX &7| Created a new region with the id {id}"
  noGame: "&c&lMineX &7| You are not in a game!"
  leftGame: "&c&lMineX &7| You have left a game!"
  lootchestGiveUsage: "&c&lMineX &7| Invalid usage try: /game lootchest give <type>"
  lootchestGive: "&c&lMineX &7| You have given yourself a {type} lootchest"
  invalidType: "&c&lMineX &7| Invalid type!"
  addspawnUsage: "&c&lMineX &7| Invalid usage try: /game addsapwn <id> <name>"
  addedSpawn: "&c&lMineX &7| You have added a new spawn named {name}"
  addextractionUsage: "&c&lMIneX &7| Invalid usage try: /game addextraction <id> <name>"
  extractionExists: "&c&lMienX &7| This extraction already exists!"
  newExtraction: "&c&lMineX &7| You have added a new extraction!"
  inGame: "&c&lMineX &7| You must be in a game to do this"
  gameLobbySetspawnUsage: "&c&lMineX &7| Invalid usage try: /game lobby setspawn <id>"
  gameLobbySpawnSet: "&c&lMineX &7| You have set the lobby spawn"
  gameLobbyTpUsage: "&c&lMineX &7| Invalid usage try: /game lobby teleport <id>"
  partyInviteUsage: "&c&lMineX &7| Invalid usage try: /party invite <player>"
  invalidPlayer: "&c&lMineX &7| Invalid player!"
  partyInvited: "&c&lMineX &7| You have been invited to join {name}'s party! Use /party join {name} to join"
  partyInvitedPlayer: "&c&lMineX &7| You have invited {name} to join your party"
  partyJoined: "&c&lMineX &7| You have joined {name}'s party!"
  partyJoinedPlayer: "&c&lMineX &7| {name} has joined your party!"
  partyMax: "&c&lMineX &7| This party is full"
  noInvite: "&c&lMineX &7| You do not have an invite from this party!"
  alreadyInParty: "&c&lMineX &7| You are already in a party!"
  partyCreated: "&c&lMineX &7| You have created a new party"
  noParty: "&c&lMineX &7| You do not have a party!"
  playerKicked: "&c&lMineX &7| You have kicked {name} from your party"
  notLeader: "&c&LMineX &7| You are not the party leader!"
  partyDisband: "&c&lMineX &7| You have disband your party"
  spawnExists: "&c&lMineX &7| A spawn with this id already exists!"
  mobspawnAdded: "&c&lMineX &7| You have added a new mobspawn at your location!"
  bankDisabled: "&c&lMineX &7| The bank has been disabled!"
  sold: "&c&lMineX &7| You have sold {amount} worth of items!"

economy:
  bank: true
  item:
    material: GOLD_INGOT
    name: "&c&lMoney"
    lore:
      - "&7Use /bank to safely store this!"


#Lootchest configuration
lootChest:
  settings:
    uncommon:
      maxItems: 6
      minItems: 3
    common:
      maxItems: 5
      minItems: 2
    rare:
      maxItems: 4
      minItems: 1
  items:
    uncommon:
      1:
        material: DIAMOND
        amount: 1
      2:
        material: STONE
        amount: 10
      3:
        material: STONE_SWORD
        amount: 1
      4:
        material: DIRT
        amount: 16
    common:
      1:
        material: DIAMOND
        amount: 6
      2:
        material: STONE
        amount: 20
      3:
        material: IRON_SWORD
        amount: 1
      4:
        material: DIRT
        amount: 32
    rare:
      1:
        material: DIAMOND
        amount: 16
      2:
        material: STONE
        amount: 32
      3:
        material: DIAMOND_SWORD
        amount: 1
      4:
        material: DIRT
        amount: 32

